I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/week5_script.rpy", line 38, in script
    heard "It would have been early 2012."
Exception: Sayer 'heard' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/week5_script.rpy", line 38, in script
    heard "It would have been early 2012."
  File "C:\Users\Tristan\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Tristan\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'heard' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Jack Sparrow Case 1.0
Fri Nov 24 18:10:15 2023
